apiVersion: v1
kind: Pod
metadata:
  name: single-container-pod
  namespace: dev
  labels:
    env: dev
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
